spring:
  liquibase.enabled: true
  datasource:
    url: jdbc:mysql://mysql:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  graphql:
    graphiql.enabled: true
    schema.printer.enabled: true

logging:
  pattern.console: '[%date{"yyyy-MM-dd''T''HH:mm:ss,SSSXXX"}] [%thread] %level %logger - %msg%n'

management:
  endpoints:
    web.base-path: /admin
    web.exposure.include: health,info,env,prometheus,metrics,startup,caches,beans
  endpoint:
    metrics.enabled: true
    export.prometheus.enabled: true
  prometheus:
    enabled: true
  health:
    livenessstate.enabled: true
    readinessstate.enabled: true
    show-details: always
    show-components: always
    probes.enabled: true
    group:
      readiness.show-components: always
      readiness.show-details: always


