version: "2"

services:
  mysql:
    image: mysql:8.0.28
    mem_limit: 500m
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    networks:
      backend:
        aliases:
          - mysql

  graphql-service:
    image: eshishkin/demo/graphql
    mem_limit: 1g
    depends_on:
      - mysql
    expose:
      - "8080"
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms256m -Xss512k -Xmx256m -XX:MaxMetaspaceSize=100M -XX:ReservedCodeCacheSize=60M -XX:+UseContainerSupport -XX:+AlwaysActAsServerClassMachine -XX:+AlwaysPreTouch
    command: [
#        "--spring.liquibase.change-log=classpath:/db/changelog/changes.xml",
#        "--logging.level.org.springframework=DEBUG",
#        "--logging.level.com.zaxxer.hikari=INFO"
    ]

    networks:
      backend:
        aliases:
          - graphql-service
networks:
  backend:
